eclipsehome=/usr/lib/eclipse
7z=/usr/bin/7za
locale=en_US
cvsuser=name
cvspass=password
db.tag=HEAD
net.tag=HEAD
client.tag=HEAD
workshop.tag=HEAD
editor.tag=HEAD
server.tag=HEAD
data.tag=HEAD
remote.server.ip=1.1.1.1
remote.server.username=name
remote.server.password=password
remote.server.basedir=/filedir
remote.server.libdir=/filedir/lib
